#!/bin/sh /etc/rc.common

START=99
USE_PROCD=1
PROG=/usr/bin/nezha-agent

start_service() {
    config_load "nezha-agent-v1"
    config_get enabled config enabled 0
    config_get config_mode config config_mode preset
    
    [ $enabled -ne 1 ] && return 1
    
    local config_file
    if [ "$config_mode" = "custom" ]; then
        config_file="/etc/config/nz_custom.yml"
        if [ ! -f "$config_file" ]; then
            return 1
        fi
    else
        config_file="/etc/config/nz.yml"
        if [ ! -f "$config_file" ]; then
            return 1
        fi
    fi
    
    procd_open_instance
    procd_set_param command $PROG -c $config_file
    procd_set_param respawn
    procd_set_param stderr 1
    procd_close_instance
}

service_triggers() {
    procd_add_reload_trigger "nezha-agent"
}

reload_service() {
    stop
    start
}
